credentials:
  username: github-username
  token: github-token

callback_url: http://example.com/callback_url
callback_secret: asdfasdfasdf

allowed_usernames:
  - username

allowed_emails:
  - email@example.com

repositories:
  - username/repository
  - username/other-repository