credentials:
  username: github-username
  token: github-token

callback_url: http://example.com/callback_url
callback_secret: asdfasdfasdf

allowed_usernames:
  - username

allowed_emails:
  - email@example.com

allowed_domains:
  - example.com

allowed_organizations:
  - organization

enabled_actions:
  - opened

skip_bootstrap: false

repositories:
  - username/repository
  - username/other-repository

non_whitelisted_template: config/non_whitelisted_template.md.erb
whitelisted_template: config/whitelisted_template.md.erb
