credentials:
  username: config-username
  token: config-token

callback_url: http://example.com/callback
callback_secret: asdfasdfasdf

allowed_usernames:
  - allowed-username

repositories:
  - username/repository
  - username/other-repository
  - other-username/repository