credentials:
  username: config-username
  token: config-token

callback_url: http://example.com/callback
callback_secret: asdfasdfasdf

allowed_usernames:
  - allowed-username

allowed_emails:
  - allowed-email@example.com

allowed_domains:
  - example.com

allowed_organizations:
  - organization

repositories:
  - username/repository
  - username/other-repository
  - other-username/repository

enabled_actions:
  - opened

non_whitelisted_template: config/template_1
whitelisted_template: config/template_2
